/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.enac.m2ihm.modaliteinteraction.canvas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author guilhem
 */
public class CanvasPanel extends javax.swing.JPanel {

    private static final int CIRCLE_DIAMETER = 10;
    private List<Point> points;

    
    /**
     * Creates new form CanvasPanel
     */
    public CanvasPanel() {
        initComponents();
        points = new ArrayList<>();
    }

    public List<Point> getPoints() {
        return points;
    }

    public void setPoints(List<Point> points) {
        this.points = points;
    }
    
    
    
        @Override
    public void paint(Graphics g) {
        super.paint(g);
        Color oldColor = g.getColor();
        if (!points.isEmpty()){
            g.setColor(Color.GREEN);
            g.fillOval((int)points.get(0).getX() - CIRCLE_DIAMETER/2, (int)points.get(0).getY()- CIRCLE_DIAMETER/2, CIRCLE_DIAMETER, CIRCLE_DIAMETER);
            g.setColor(Color.BLACK);
            for (int i=0; i < points.size() - 1; i++){
                g.drawLine((int)points.get(i).getX(), (int)points.get(i).getY(), 
                        (int)points.get(i + 1).getX(), (int)points.get(i + 1).getY());
            }
            g.setColor(Color.RED);
            g.fillOval((int)points.get(points.size() - 1).getX() - CIRCLE_DIAMETER/2, 
                    (int)points.get(points.size() - 1).getY() - CIRCLE_DIAMETER/2, CIRCLE_DIAMETER, CIRCLE_DIAMETER);
        }
        g.setColor(oldColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
