/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.enac.m2ihm.modaliteinteraction.moteurfusion;

/**
 *
 * @author guilhem
 */
public enum FusionMotorState {
    IDLE,
    CREATION,
    CREATION_WAIT_FOR_KEYWORD,
    CREATION_WAIT_FOR_CLIC_POSITION,
    CREATION_WAIT_FOR_CLIC_COLOR,
    DEPLACEMENT,
    DEPLACEMENT_WAIT_FOR_CLIC_POSITION_1,
    DEPLACEMENT_WAIT_FOR_KEYWORD,
    DEPLACEMENT_WAIT_FOR_CLIC_SHAPE_1,
    DEPLACEMENT_WAIT_NEXT_SHAPE,
    DEPLACEMENT_WAIT_CLIC_POSITION_UPDATE,
    DEPLACEMENT_WAIT_NEXT_POSITION,
    DEPLACEMENT_WAIT_CLIC_SHAPE_UPDATE,
    DEPLACEMENT_WAIT_KEYWORD_OBJECT,
    DEPLACEMENT_WAIT_CLIC_SHAPE_2,
    DEPLACEMENT_WAIT_CLIC_POSITION_2,
    DEPLACEMENT_WAIT_KEYWORD_POSITION,
    DEPLACEMENT_COLOR,
    SUPPRESSION,
    SUPPRESSION_WAIT_CLIC,
    SUPPRESSION_WAIT_KEYWORD_OBJECT,
    SUPPRESSION_WAIT_COLOR,
    SUPPRESSION_WAIT_CLIC_UPDATE,
    SUPPRESSION_WAIT_KEYWORD_OBJECT_UPDATE
}
